"""Declared column lists for the datasets this package reads.

Validation used to rediscover the columns of every dataset on every session opening, by
opening each file and reading its header. That is 11 file opens per initialization to learn
something that does not change - and on network storage each open is a round trip, which is the
cost that matters rather than the milliseconds.

So the columns are declared instead, in `dataset_columns.json`, generated by `build.py` and
committed so a change shows up in a diff.

**Keyed by client, not shared.** Four of the eleven datasets carry different columns per
client: capstone's `alerts_detail` has 113 columns against CDA's 54, and its `predictive_motor`
has 337 against 128. A single shared list would be wrong for somebody.

**Trusted, with two lines of defence, because "definitive" means "for now".** If a column is
renamed upstream, validation would report a source as valid against a schema that no longer
holds. What catches it:

1. Every query resolves its columns through `_resolve_column`, which returns ``None`` and
   raises a specific error rather than producing a wrong answer. The failure moves from the
   session opening to the moment that column is used - later, but louder.
2. `verify_against_disk` compares the declaration with the real headers once per container, in
   the background, and publishes the result in `/diagnostics`.

And `CAMPBELL_AI_FROZEN_SCHEMA=false` returns to reading headers without deploying code.
"""

from __future__ import annotations

import json
import logging
import os
import threading
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("campbell_ai.schema")

SCHEMA_FILE = Path(__file__).with_name("dataset_columns.json")

_LOCK = threading.Lock()
_LOADED: Optional[dict[str, Any]] = None
_LOAD_ERROR: str = ""


def frozen_schema_enabled() -> bool:
    """Whether declared columns may be used instead of reading a header."""
    raw = os.getenv("CAMPBELL_AI_FROZEN_SCHEMA")
    if raw is None:
        return True
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _load() -> dict[str, Any]:
    """Read the declaration once per process. A missing or broken file is not fatal."""
    global _LOADED, _LOAD_ERROR
    with _LOCK:
        if _LOADED is not None:
            return _LOADED
        try:
            document = json.loads(SCHEMA_FILE.read_text(encoding="utf-8"))
            clients = document.get("clients")
            if not isinstance(clients, dict):
                raise ValueError("falta el mapa 'clients'")
            _LOADED = clients
        except Exception as exc:  # noqa: BLE001 - degrade to reading headers, never fail
            _LOAD_ERROR = f"{type(exc).__name__}: {exc}"
            logger.warning(
                "No se pudo leer %s (%s); se leeran las cabeceras como antes",
                SCHEMA_FILE.name,
                _LOAD_ERROR,
            )
            _LOADED = {}
        return _LOADED


def declared_columns(client: str, dataset_key: str, suffix: str) -> Optional[list[str]]:
    """Declared columns for one dataset of one client, or ``None`` to read the header.

    ``suffix`` guards against a format change: a dataset that used to be a CSV and is now a
    parquet is a different file, and its declaration should not be believed until regenerated.
    """
    if not frozen_schema_enabled():
        return None
    entry = _load().get(str(client).strip().lower(), {}).get(dataset_key)
    if not isinstance(entry, dict):
        return None
    if str(entry.get("format", "")).lower() != suffix.lstrip(".").lower():
        return None
    columns = entry.get("columns")
    if not isinstance(columns, list) or not columns:
        return None
    return [str(column) for column in columns]


def describe() -> dict[str, Any]:
    """What the declaration holds, for the diagnostics payload."""
    clients = _load()
    return {
        "file": str(SCHEMA_FILE),
        "enabled": frozen_schema_enabled(),
        "loaded": bool(clients),
        "error": _LOAD_ERROR or None,
        "clients": {
            client: sum(len(entry.get("columns", [])) for entry in datasets.values())
            for client, datasets in clients.items()
        },
        "verification": verification_report(),
    }


def verify_against_disk(repository: Any) -> dict[str, Any]:
    """Compare the declaration with the real headers. Returns what disagreed.

    Run once per container, in the background: this reads every header, which is exactly the
    work the declaration exists to avoid on the hot path. Paying it once, off the critical
    path, is what turns a silent divergence into a visible one.
    """
    from src.campbell_ai.data import DATASETS

    checked = 0
    mismatches: list[dict[str, Any]] = []
    for client, datasets in _load().items():
        for spec in DATASETS:
            if spec.key not in datasets:
                continue
            try:
                path = repository.dataset_path(spec.key, client)
            except Exception:
                continue
            if not path.exists():
                # Now that validation assumes presence, this is the one place that actually
                # looks - so an absent dataset has to be reported, not skipped.
                mismatches.append(
                    {"client": client, "dataset": spec.key, "missing_file": str(path)}
                )
                continue
            try:
                real = repository.read_columns(path)
            except Exception as exc:  # noqa: BLE001 - a failed read is not a mismatch
                mismatches.append(
                    {"client": client, "dataset": spec.key, "error": f"{type(exc).__name__}: {exc}"}
                )
                continue
            checked += 1
            expected = [str(c) for c in datasets[spec.key].get("columns", [])]
            if real != expected:
                missing = [c for c in expected if c not in real]
                added = [c for c in real if c not in expected]
                mismatches.append(
                    {
                        "client": client,
                        "dataset": spec.key,
                        "declared": len(expected),
                        "real": len(real),
                        # Truncated: the point is to notice, not to print a schema.
                        "missing": missing[:10],
                        "added": added[:10],
                    }
                )
    report = {"checked": checked, "mismatches": mismatches}
    if mismatches:
        logger.warning(
            "El esquema declarado no coincide con los datos en %s casos: %s",
            len(mismatches),
            [f"{m.get('client')}/{m.get('dataset')}" for m in mismatches],
        )
    else:
        logger.info("Esquema declarado verificado contra %s datasets, sin diferencias", checked)
    return report


# Result of the last verification, for `/diagnostics`. A divergence between the declared
# schema and the data is exactly the failure mode the declaration introduces, so it has to be
# visible somewhere an operator looks - not only in a log line that may have rotated away.
_VERIFICATION: dict[str, Any] = {"state": "pending"}
_VERIFIER: Optional[threading.Thread] = None


def verification_report() -> dict[str, Any]:
    """What the last schema verification found."""
    return dict(_VERIFICATION)


def start_schema_verification(repository: Any) -> bool:
    """Verify the declaration against disk once, in the background. True if started.

    In a thread and not awaited: it reads every header, which is the work the declaration
    exists to avoid on the hot path. Paying it once per container, off the critical path, is
    what keeps a silent divergence from staying silent.
    """
    global _VERIFIER
    if not frozen_schema_enabled():
        _VERIFICATION.update({"state": "disabled"})
        return False
    if _VERIFIER is not None and _VERIFIER.is_alive():
        return False

    def run() -> None:
        try:
            report = verify_against_disk(repository)
            _VERIFICATION.clear()
            _VERIFICATION.update({"state": "verified", **report})
        except Exception as exc:  # noqa: BLE001 - a failed check must not kill the process
            _VERIFICATION.clear()
            _VERIFICATION.update({"state": "error", "error": f"{type(exc).__name__}: {exc}"})
            logger.warning("La verificacion del esquema declarado fallo", exc_info=True)

    _VERIFIER = threading.Thread(target=run, name="campbell-schema-verify", daemon=True)
    _VERIFIER.start()
    return True


def reset() -> None:
    """Forget the loaded declaration. For tests."""
    global _LOADED, _LOAD_ERROR
    with _LOCK:
        _LOADED = None
        _LOAD_ERROR = ""
    _VERIFICATION.clear()
    _VERIFICATION.update({"state": "pending"})
